services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mirofish-backend
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - ZEP_API_KEY=${ZEP_API_KEY}
      - FLASK_DEBUG=False
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5001/health')",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: mirofish-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
#    labels:
#      - "traefik.http.middlewares.miroauth.basicauth.users=gr:$$2y$$05$$X07mZVWM7abAHOM3Btdr0OJ6jb3lyDu0S62D73.fvFCy8ELxjWY3C"
#     - "traefik.http.routers.http-0-acgoo4kwk0swcsg8g88cos8g-frontend.middlewares=miroauth"
#     - "traefik.http.routers.https-0-acgoo4kwk0swcsg8g88cos8g-frontend.middlewares=miroauth"
